// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Question struct {
	ID        string
	Name      string
	Url       string
	Solved    string
	UpdatedAt time.Time
}
