// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Question struct {
	ID         string
	Name       string
	Url        string
	Solved     string
	Difficulty string
	UpdatedAt  time.Time
}
